### ISSUE TITLE
optimize deck from cards upgrades commander

### ISSUE THREAD

**Issue by technophile77** [zachanassian/tu_optimize#10]
When optimizing my deck with owned cards, the optimizer swaps out Halcyon-1 for Halcyon, even though I don't have it. 

F:\goog\alex\tyrant\sim\tu_optimize>tu_optimize.exe "Halcyon-1, Nimbus-4, Havoc,
 Vigil, Pantheon Progeny-5, Shining Sanctuary, Blitz Guard, Blitz Plate, Dutiful
 Veteran" pvp75k1 -o=data\rallyraider.txt climb 100000
Your Deck: [QEAdA6CdKeiC-HA-HE-Hc] Halcyon, Nimbus-4, Havoc, Vigil, Pantheon Pro
geny-5, Shining Sanctuary, Blitz Guard, Blitz Plate, Dutiful Veteran
Enemy's Deck: [QEAfIPJOLKgT+i-BQ-MJ-Ml] Halcyon, Tartarus Scion, Nimbus, Masterw
ork Aegis, Xeno Suzerain, Sanctuary, Sanctuary, Primus, Crushing Anvil, Windreav
er
5.101 (5101 / 100000)
5.101: Halcyon, Nimbus-4, Havoc, Vigil, Pantheon Progeny-5, Shining Sanctuary, B
litz Guard, Blitz Plate, Dutiful Veteran
Evaluated 149 decks (180817 + 18696 simulations).
Optimized Deck: 5.101: Halcyon, Nimbus-4, Havoc, Vigil, Pantheon Progeny-5, Shin
ing Sanctuary, Blitz Guard, Blitz Plate, Dutiful Veteran

contents of rallyraider.txt:
F:\goog\alex\tyrant\sim\tu_optimize>type data\rallyraider.txt
//Commanders
Ascaris
Cyrus
Malika
Maion
Terrogor
Brood Mother-1
Octane-1
Empress-4
Vyander-1
Dracorex-1
//Halcyon-1
Typhon Vex-1
Alaric-1
Krellus-1
Yurich-4
//Deck
Carbine (2)
Assembly Plant
Blitz Guard
Blitz Plate
Dutiful Veteran
//Indebted Veteran
// Honor-Bound Veteran
Havoc
Vigil
Shining Sanctuary
//Unleveled cards
Brood Walker (4)
//Terminator Mech
Terminator
Draconian Queen-1
Nexusisite-1
//Stinger Barrage
Stinger-1 (2)
Iron Maiden-1
Missile Silo-5
Rampage-1 (2)
//Rampage Rumbler
Reaver-1 (2)
//Destruction Reaver
Pantheon Progeny-5
Dreadship-1
Mongore-1
Nimbus-4
Tiamat-1

**Comment by zachanassian** [comment]
Confirmed bug with
tu_optimize.exe "Halcyon-1, Nimbus-4" "Halcyon, Nimbus-4" sim 1000
it is related to this entry in cards.xml

<pre>
    &lt;unit&gt;
        &lt;id&gt;1997&lt;/id&gt;
        &lt;name&gt;Halcyon&lt;/name&gt;
        &lt;picture&gt;younghalcyon.jpg&lt;/picture&gt;
        &lt;attack&gt;0&lt;/attack&gt;
        &lt;health&gt;1&lt;/health&gt;
        &lt;rarity&gt;3&lt;/rarity&gt;
        &lt;type&gt;1&lt;/type&gt;
    &lt;/unit&gt;
</pre>

Short term workaround remove this entry from cards.xml

**Comment by zachanassian** [comment]
Fixed with version 1.0.2

**Comment by technophile77** [comment]
Wow, thanks for the quick fix!
