### ISSUE TITLE
[Feature] Battleground strike effect

### ISSUE THREAD

**Issue by technophile77** [zachanassian/tu_optimize#11]
Can you add the enhanced strike battleground effect for the upcoming guild war?

**Comment by zachanassian** [comment]
Is this confirmed? Any dev post I missed?

Won't promise anything but feature seems feasible.

**Comment by whatchamccallum** [comment]
Explosive volley. Sounds like it to me

**Comment by zachanassian** [comment]
Confirmed by [Rudgutter](http://www.kongregate.com//forums/338/topics/391553?page=1#posts-7913833)

Will add it in Version 1.1 released once new missions and cards are added (post Evrane)

**Comment by zachanassian** [comment]
Version 1.1 released
