### ISSUE TITLE
[FEATURE] Deck groupings

### ISSUE THREAD

**Issue by technophile77** [zachanassian/tu_optimize#12]
Can you add a way to create a group of decks?  I'm running pvp sims, and have about 50 decks that I want to sim my deck against. I have added each of them to customdecks.txt, but it's a lot of typing to list all 50. Can you setup something so I can reference them as a group?

**Comment by zachanassian** [comment]
I am using batch files for grouping decks. http://zachanassian.github.io/tu_optimize/faq.html#batch

It is cumbersome and a better support is possible, but I won't implement this in the near future. But if somebody else does it and send me a pull request I would add it.

**Comment by technophile77** [comment]
I understand, maybe I'll work on it if keeps bugging me.

**Comment by whatchamccallum** [comment]
I've thought about diving in and attempting to muli-thread this. Using a
single core at 100% is just missing lots of available horse power to work
through these simulations. I batch simulate against a bunch of decks and
attempt to run climb against them. The one little CPU is very unhappy at me
and feels slightly abused

**Comment by zachanassian** [comment]
whatchamccallum: not sure if multi threading is related to this feature. If not you could open another issue.

However tu_optimize supports multithreading. There is the option -t to specify the number of threads to use and -t 4 is the default. If I check in task monitor I can can utilize all CPU cores during a simulation. if you are really on a pc with just one cpu -t 1 might help to keep the one little CPU happier :-)

Another remark: If you do a lot of climb sims it helps to keep ownedcards.txt small. So if your deck consists of only quad fusions you could remove all normal epics and lower from ownedcards if you share my judgement that these cards won't improve your deck.

**Comment by whatchamccallum** [comment]
Sorry very indirectly related. Thank you I'll test and open a different
issue of I have a problem. Also myself for not reading close enough.

**Comment by zachanassian** [comment]
Version 1.1 will allow entries like this in customdecks.txt

<pre>
test_group: eerie-spam:0.2;nbd-spam:0.8
</pre>

**Comment by zachanassian** [comment]
Version 1.1 released
