### ISSUE TITLE
cards.xml - naming issue

### ISSUE THREAD

**Issue by ghost** [zachanassian/tu_optimize#13]
Bombardment Tank should be Bombardment Tanks. The gauntlet deck GT04 in customdecks.txt has the correct name but cards.xml does not so the default gauntlet throws a warning.

minor issue, but just so you know!

**Comment by zachanassian** [comment]
cards.xml is a copy from the TU server. So it is always correct. 

DEV changed the name from Bombardment Tanks to Bombardment Tank.

Issue is now corrected in Version 1.1.2 - thanks for reporting
