### ISSUE TITLE
Differing results when running identical decks, one is its own custom deck, other is part of a batch

### ISSUE THREAD

**Issue by sammyc914** [zachanassian/tu_optimize#24]
So I was running my own deck against a batch of Eclipse decks, and got wildly different results depending on the source of my deck when using fort structures and enhance skill effects.  When I just ran in normal surge mode, the results were identical.

For reference was running this:  tu_optimize sammy eclipsebatch yf "Sky Fortress(2)" ef "Sky Fortress" -s -e "Berserk 3" sim 10000

When I used my deck as its own individual custom deck, I got a winrate of 68%.  When I used my deck from the eclipse batch (46th deck in batch), I got a winrate of 30.9%.  I also tried copying the hash used for my deck in the batch and placing it in its own individual custom deck, and that also gave me a winrate of 68%, so it is not an error with the hash.  

And as mentioned above, when running without structures/skill enhance,  the results from individual deck and batch deck were identical.

**Comment by zachanassian** [comment]
BUG confirmed. If "your deck" is also part of "enemy deck" batch the efort structures are used also for the attacker. See Your Fortress Cards: Minefield, Minefield

<pre>
>tu_optimize mydeck "mydeck;mydeck" yf "Sky Fortress(2)" ef "Minefield(2)" sim 10000
Attacking Fortress Structure(s) Used: Sky Fortress(2)
Defending Fortress Structure(s) Used: Minefield(2)
Your Fortress Cards: Minefield, Minefield
Enemy's Fortress Cards: Minefield, Minefield
</pre>

**Comment by zachanassian** [comment]
Fixed with Version 2.0.1
