### ISSUE TITLE
Finding discrepancy with other sims

### ISSUE THREAD

**Issue by savoirfairemn** [zachanassian/tu_optimize#32]
Hi, zachanassian - Sorry I don't have the knowledge to include any more detail, but when running a sim for a friend, I keep getting very different results with your sim compared to tyrantwars.com and tyrantsim.weebly.com, which are more in line.

For example, running his deck (Barracus Lv.4, Starformer Lv.6, Arch Nova Elite Lv.6, Ayrkrane Vik Lv.6, Trampling Anvil Lv.6, Auger Lv.5, Spiteful Raptor Lv.6, Forsaken Beetle Lv.6) in order against Infested Rastax, I get >99% compared to ~85% with the other sims.  I'm guessing there might be a problem with the implementation of corrode?

**Comment by zachanassian** [comment]
Not sure where you get 99%. Are you using 2.4.0?

<pre>
>tu_optimize "Barracus-4,Starformer,Arch Nova Elite,Ayrkrane Vik,Trampling Anvil,Auger-5,Spiteful Raptor, Forsaken Beetle" "Infested Rastax" -r sim 10000
Your Deck: [SmO6-dD-GV-WR-SB-Iw-I8] Barracus-4, Starformer, Arch Nova Elite, Ayrkrane Vik, Trampling Anvil, Auger-5, Spiteful Raptor, Forsaken Beetle
Enemy's Deck: [U4BhGrgZ-J5-J/-hM-ik-iq-iw+i] Infested Rastax, Sarcous Grub, Sarcous Grub, Blood Rider, Bulbous Slug, Mephalus, Venomous Raptor, Narscious the Horror, Narscious, Malg...
win%: 80.22 (8022 / 10000)
stall%: 1.81 (181 / 10000)
loss%: 17.97 (1797 / 10000)
</pre>

**Comment by zachanassian** [comment]
Seems like issue is solved. Close.
