### ISSUE TITLE
Performance of climb

### ISSUE THREAD

**Issue by fverde** [zachanassian/tu_optimize#33]
Hello,
I have noticed from 19 to 20 cards (excluding commander) my win rate drops precipitously. I was wondering if this is a bug.

Command:
tu_optimize "Barracus, Apex Overdrive, Crushing Anvil, Auger Bore, Tartarus Brood, Deranged Fanatic, Ironclad Troop, Razogoth's Legacy, Defiler,  Narscious, Air Superior, Shining Sanctuary, Xillaclaw, Valiant Knight, Messale, Defiance, Xanadu Tetra, Alloy Ram, Tumbler, Arch Nova Elite" "GDR Rebooted" -r -o climb 10000

Result:
83.07: Barracus, Auger Bore, Tumbler, Arch Nova Elite, Shining Sanctuary, Deranged Fanatic, Tartarus Brood, Air Superior, Narscious

Command:
tu_optimize "Barracus, Apex Overdrive, Crushing Anvil, Auger Bore, Tartarus Brood, Deranged Fanatic, Ironclad Troop, Razogoth's Legacy, Defiler,  Narscious, Air Superior, Shining Sanctuary, Xillaclaw, Valiant Knight, Messale, Defiance, Xanadu Tetra, Alloy Ram, Tumbler, Arch Nova Elite, Assailant" "GDR Rebooted" -r -o climb 10000
Result:
Optimized Deck: 56.76: Barracus, Auger Bore, Arch Nova Elite, Xillaclaw, Shining Sanctuary, Tumbler, Apex Overdrive, Tartarus Brood, Valiant Knight, Deranged Fanatic, Air Superior, Alloy Ram, Xanadu Tetra, Ironclad Troop, Messale, Assailant

**Comment by zachanassian** [comment]
Start with a valid deck as mydeck. Currently you are trying to build a 20card deck against GDR Reboot.

eg. tu_optimize "Barracus, Apex Overdrive, Crushing Anvil, Auger Bore, Tartarus Brood, Deranged Fanatic, Ironclad Troop" "GDR Rebooted" -r -o climb 10000 

and put all your cards in ownedcards.txt

for more details check [here](http://zachanassian.github.io/tu_optimize/#owndecks)

**Comment by fverde** [comment]
Hello,
Thank you for the response. I understand what I am trying to do. I have been using large card pools to test which cards to focus on for many months. I actually use the GUI and put all the cards there. I do not use ownedcards.txt which just gives a warning and proceeds to run. I am not a coder. I am just making an observation. Your work is greatly appreciated! (although likely largely uncompenstated).

**Comment by zachanassian** [comment]
Hello,

If you are sure you know what you are doing then I rest my case. For me it looks strange to optimize a 20 card deck if the game only allows 10 card decks at max. However if you do not want to use ownedcards.txt the new version 2.5.0 allows you to add all your cards with as an option using <code>-o=<cards></code>

In your example:

<pre>
tu_optimize "Barracus, Apex Overdrive, Crushing Anvil, Auger Bore, Tartarus Brood" "GDR Rebooted" -r -o="Deranged Fanatic, Ironclad Troop, Razogoth's Legacy, Defiler, Narscious, Air Superior, Shining Sanctuary, Xillaclaw, Valiant Knight, Messale, Defiance, Xanadu Tetra, Alloy Ram, Tumbler, Arch Nova Elite" climb 10000
...
Optimized Deck: 83.33: Barracus, Auger Bore, Arch Nova Elite, Shining Sanctuary, Tartarus Brood, Deranged Fanatic, Air Superior, Narscious
</pre>

If you add Assailant

<pre>
tu_optimize "Barracus, Apex Overdrive, Crushing Anvil, Auger Bore, Tartarus Brood" "GDR Rebooted" -r -o="Deranged Fanatic, Ironclad Troop, Razogoth's Legacy, Defiler, Narscious, Air Superior, Shining Sanctuary, Xillaclaw, Valiant Knight, Messale, Defiance, Xanadu Tetra, Alloy Ram, Tumbler, Arch Nova Elite, Assailant" climb 10000
...
Optimized Deck: 82.99: Barracus, Auger Bore, Arch Nova Elite, Shining Sanctuary, Tartarus Brood, Deranged Fanatic, Razogoth's Legacy, Air Superior
</pre>

So you get very similar results

**Comment by zachanassian** [comment]
Closed.

**Comment by sacrosanctic** [comment]
In this example "tu_optimize "Barracus, Apex Overdrive, Crushing Anvil, Auger Bore, Tartarus Brood" "GDR Rebooted" -r -o="Deranged Fanatic, Ironclad Troop, Razogoth's Legacy, Defiler, Narscious, Air Superior, Shining Sanctuary, Xillaclaw, Valiant Knight, Messale, Defiance, Xanadu Tetra, Alloy Ram, Tumbler, Arch Nova Elite, Assailant, Apex Overdrive" climb 10000"

What does "-r" do?
If I have one apex overdrive, but I put 1 in my deck and 1 in owned cards, does tu_optimize think I have 2 and optimize for that?
