### ISSUE TITLE
False positive virus alert?

### ISSUE THREAD

**Issue by Karel-van-de-Plassche** [zachanassian/tu_optimize#35]
Trying to share the SimpleTUOptimizeStarter.exe via Google Drive gives a virus warning, rendering the file un-sharable. (https://drive.google.com/file/d/0B1zH1qEQD_zWcml3b0cydzd5aUU/edit?usp=sharing) All other files don't generate a virus alert.

**Comment by zachanassian** [comment]
This has already been discussed [here](https://github.com/zachanassian/tu_optimize)

SimpleTUOptimizeStarter.exe is generated out of SimpleTUOptimizeStarter.ahk. [Details](http://zachanassian.github.io/tu_optimize/faq.html#ahk) 
Autohotkey is a low level tool that is known to cause false positives in virus detection software. So my bet is that this is the case here as well.

However I do not and can not gurantee that SimpleTUOptimizeStarter.exe or any other part of tu_optimize is virus free. So

a) you do not use tu_optimize at all
b) you do not use SimpleTUOptimizeStarter.exe
c) install autohotkey and use the SimpleTUOptimizeStarter.ahk script
d) you check the source code and [compile your own version](http://zachanassian.github.io/tu_optimize/install.html#compile of tu_optimize).

While option a) is savest option d) is the one I recommend.

Edit: [Symantec WS.Reputation.1](http://www.symantec.com/security_response/writeup.jsp?docid=2010-051308-1854-99) : Shows that this is a heuristic check. So if some kid build a malicious exe from an .ahk file and compiled it the "wisdom of the crowd" will lead to the fact that all exe from an .ahk files are considered as malicious. Nevertheless I uploaded a version to Symantec's whitelist program but not sure when/if this will help.
