### ISSUE TITLE
Bug in Enhance Heal and Enhance Rally

### ISSUE THREAD

**Issue by zachanassian** [zachanassian/tu_optimize#44]
[Original message](http://www.kongregate.com/forums/338/topics/390807?page=19#posts-8181862) - Thx rh75 and SimeonH for reporting this bug

Bug Report: War effect errors:
Enhance Heal
Enhance Rally

The war effects are applied to units that have that specific skill, however structures abilities are enhanced if they target someone who has the enhanced ability. 
E.G.
SacredS and ZH and Crogall Static are played within War with enhance rally 3.
The ZH is given enhance rally 3.
SacredS rallies the ZH for 2 ( + 3 from enhance rally – BUGGED)
SacredS rallies Crogall Static for 2 (no effect from enhance rally)
ZH rallies itself for 2 ( + 3 from enhance rally)
ZH rallies Crogall Static for 2 (no effect from enhance rally – BUGGED)

Edit – Affects both structures and assault units. Have provided Crogall Static as unit without Rally, ZH as unit with Rally, and structure with Rally as examples.

**Comment by zachanassian** [comment]
<pre>
tu_optimize "Alaric, Sacred Sanctuary, Zodiac Harbinger, Crogall Static" "Alaric, Vigil(5)" ordered -e "Rally 3" +v debug
...
TURN 9 begins for Commander [Alaric hp:46]
Assault 1 [Crogall Static att:5 hp:22 cd:1, evades left 3] reduces its timer
Evaluating Commander [Alaric hp:46] skill Enhance Rally all 3
Possible targets of Enhance Rally:
+ Assault 0 [Zodiac Harbinger att:5 hp:12]
Commander [Alaric hp:46] Enhance Rally (3) on Assault 0 [Zodiac Harbinger att:5 hp:12]
Evaluating Commander [Alaric hp:46] skill Enhance Evade all 1
Possible targets of Enhance Evade:
+ Assault 1 [Crogall Static att:5 hp:22, evades left 3]
Commander [Alaric hp:46] Enhance Evade (1) on Assault 1 [Crogall Static att:5 hp:22, evades left 3]
Evaluating Commander [Alaric hp:46] skill Heal righteous 3
Possible targets of Heal:
+ Assault 0 [Zodiac Harbinger att:5 hp:12, enhance rally 3]
Commander [Alaric hp:46] Heal (3) on Assault 0 [Zodiac Harbinger att:5 hp:12, enhance rally 3]
Evaluating Commander [Alaric hp:46] skill Strike all 1
Possible targets of Strike:
+ Assault 0 [Vigil att:5 hp:12 cd:2]
+ Assault 1 [Vigil att:5 hp:12 cd:3]
Commander [Alaric hp:46] Strike (1) on Assault 0 [Vigil att:5 hp:12 cd:2]
Assault 0 [Vigil att:5 hp:12 cd:2] takes 1 damage
Commander [Alaric hp:46] Strike (1) on Assault 1 [Vigil att:5 hp:12 cd:3]
Assault 1 [Vigil att:5 hp:12 cd:3] takes 1 damage
Evaluating Structure 0 [Sacred Sanctuary hp:21] skill Heal all 3
Evaluating Structure 0 [Sacred Sanctuary hp:21] skill Rally all 2
Possible targets of Rally:
+ Assault 0 [Zodiac Harbinger att:5 hp:13, enhance rally 3]
+ Assault 1 [Crogall Static att:5 hp:22, evades left 4, enhance evade 1]
Structure 0 [Sacred Sanctuary hp:21] Rally (2) on Assault 0 [Zodiac Harbinger att:5 hp:13, enhance rally 3]
Structure 0 [Sacred Sanctuary hp:21] Rally (2) on Assault 1 [Crogall Static att:5 hp:22, evades left 4, enhance evade 1]
Evaluating Structure 0 [Sacred Sanctuary hp:21] skill Weaken 4
Evaluating Assault 0 [Zodiac Harbinger att:5+5(rallied)=10 hp:13, enhance rally 3] skill Heal all righteous 2
Evaluating Assault 0 [Zodiac Harbinger att:5+5(rallied)=10 hp:13, enhance rally 3] skill Rally all righteous 2
Possible targets of Rally:
+ Assault 0 [Zodiac Harbinger att:5+5(rallied)=10 hp:13, enhance rally 3]
+ Assault 1 [Crogall Static att:5+2(rallied)=7 hp:22, evades left 4, enhance evade 1]
Assault 0 [Zodiac Harbinger att:5+5(rallied)=10 hp:13, enhance rally 3] Rally (2) on Assault 0 [Zodiac Harbinger att:5+5(rallied)=10 hp:13, enhance rally 3]
Assault 0 [Zodiac Harbinger att:5+10(rallied)=15 hp:13, enhance rally 3] Rally (2) on Assault 1 [Crogall Static att:5+2(rallied)=7 hp:22, evades left 4, enhance evade 1]
Assault 0 [Zodiac Harbinger att:5+10(rallied)=15 hp:13, enhance rally 3] attacks Assault 0 [Vigil att:5 hp:11 cd:2] for 15-[3(armored)]=12 damage
Assault 0 [Vigil att:5 hp:11 cd:2] takes 12 damage
Assault 0 [Vigil att:5 hp:0 cd:2] dies
Evaluating Assault 1 [Crogall Static att:5+4(rallied)=9 hp:22, evades left 4, enhance evade 1] skill Strike 5
Possible targets of Strike:
+ Assault 1 [Vigil att:5 hp:11 cd:3]
Assault 1 [Crogall Static att:5+4(rallied)=9 hp:22, evades left 4, enhance evade 1] Strike (5) on Assault 1 [Vigil att:5 hp:11 cd:3]
Assault 1 [Vigil att:5 hp:11 cd:3] takes 5 damage
Evaluating Assault 1 [Crogall Static att:5+4(rallied)=9 hp:22, evades left 4, enhance evade 1] skill Weaken all 2
Assault 1 [Crogall Static att:5+4(rallied)=9 hp:22, evades left 4, enhance evade 1] attacks Assault 1 [Vigil att:5 hp:6 cd:3] for 9-[3(armored)]=6 damage
Assault 1 [Vigil att:5 hp:6 cd:3] takes 6 damage
Assault 1 [Vigil att:5 hp:0 cd:3] dies
TURN 9 ends for Commander [Alaric hp:46]
...
</pre>

Error 1: Evaluating Assault 0 [Zodiac Harbinger att:5+5(rallied)=10 hp:13, enhance rally 3] skill Heal all righteous 2
should be: Zodiac Harbinger att:5+2(rallied)

Error 2: Evaluating Assault 1 [Crogall Static att:5+4(rallied)=9 hp:22, evades left 4, enhance evade 1] skill Strike 5
should be: Crogall Static att:5+7(rallied)

**Comment by gramik** [comment]
I fixed it and send pull request. See the details in the pull request.

**Comment by zachanassian** [comment]
Fixed in version 3.3.2

<pre>
TURN 9 begins for Commander [Alaric hp:46]
Assault 1 [Crogall Static att:5 hp:22 cd:1, evades left 3] reduces its timer
Evaluating Commander [Alaric hp:46] skill Enhance Rally all 3
Possible targets of Enhance Rally:
+ Assault 0 [Zodiac Harbinger att:5 hp:12]
Commander [Alaric hp:46] Enhance Rally (3) on Assault 0 [Zodiac Harbinger att:5 hp:12]
Evaluating Commander [Alaric hp:46] skill Enhance Evade all 1
Possible targets of Enhance Evade:
+ Assault 1 [Crogall Static att:5 hp:22, evades left 3]
Commander [Alaric hp:46] Enhance Evade (1) on Assault 1 [Crogall Static att:5 hp:22, evades left 3]
Evaluating Commander [Alaric hp:46] skill Heal righteous 3
Possible targets of Heal:
+ Assault 0 [Zodiac Harbinger att:5 hp:12, enhance rally 3]
Commander [Alaric hp:46] Heal (3) on Assault 0 [Zodiac Harbinger att:5 hp:12, enhance rally 3]
Evaluating Commander [Alaric hp:46] skill Strike all 1
Possible targets of Strike:
+ Assault 0 [Vigil att:5 hp:12 cd:1]
+ Assault 1 [Vigil att:5 hp:11 cd:2]
+ Assault 2 [Vigil att:5 hp:12 cd:3]
Commander [Alaric hp:46] Strike (1) on Assault 0 [Vigil att:5 hp:12 cd:1]
Assault 0 [Vigil att:5 hp:12 cd:1] takes 1 damage
Commander [Alaric hp:46] Strike (1) on Assault 1 [Vigil att:5 hp:11 cd:2]
Assault 1 [Vigil att:5 hp:11 cd:2] takes 1 damage
Commander [Alaric hp:46] Strike (1) on Assault 2 [Vigil att:5 hp:12 cd:3]
Assault 2 [Vigil att:5 hp:12 cd:3] takes 1 damage
Evaluating Structure 0 [Sacred Sanctuary hp:21] skill Heal all 3
Evaluating Structure 0 [Sacred Sanctuary hp:21] skill Rally all 2
Possible targets of Rally:
+ Assault 0 [Zodiac Harbinger att:5 hp:13, enhance rally 3]
+ Assault 1 [Crogall Static att:5 hp:22, evades left 4, enhance evade 1]
Structure 0 [Sacred Sanctuary hp:21] Rally (2) on Assault 0 [Zodiac Harbinger att:5 hp:13, enhance rally 3]
Structure 0 [Sacred Sanctuary hp:21] Rally (2) on Assault 1 [Crogall Static att:5 hp:22, evades left 4, enhance evade 1]
Evaluating Structure 0 [Sacred Sanctuary hp:21] skill Weaken 4
Possible targets of Weaken:
+ Assault 0 [Vigil att:5 hp:11 cd:1]
Structure 0 [Sacred Sanctuary hp:21] Weaken (4) on Assault 0 [Vigil att:5 hp:11 cd:1]
Evaluating Assault 0 [Zodiac Harbinger att:5+2(rallied)=7 hp:13, enhance rally 3] skill Heal all righteous 2
Evaluating Assault 0 [Zodiac Harbinger att:5+2(rallied)=7 hp:13, enhance rally 3] skill Rally all righteous 2
Possible targets of Rally:
+ Assault 0 [Zodiac Harbinger att:5+2(rallied)=7 hp:13, enhance rally 3]
+ Assault 1 [Crogall Static att:5+2(rallied)=7 hp:22, evades left 4, enhance evade 1]
Assault 0 [Zodiac Harbinger att:5+2(rallied)=7 hp:13, enhance rally 3] Rally (5) on Assault 0 [Zodiac Harbinger att:5+2(rallied)=7 hp:13, enhance rally 3]
Assault 0 [Zodiac Harbinger att:5+7(rallied)=12 hp:13, enhance rally 3] Rally (5) on Assault 1 [Crogall Static att:5+2(rallied)=7 hp:22, evades left 4, enhance evade 1]
Assault 0 [Zodiac Harbinger att:5+7(rallied)=12 hp:13, enhance rally 3] attacks Assault 0 [Vigil att:5-4(weakened)=1 hp:11 cd:1] for 12-[3(armored)]=9 damage
Assault 0 [Vigil att:5-4(weakened)=1 hp:11 cd:1] takes 9 damage
Evaluating Assault 1 [Crogall Static att:5+7(rallied)=12 hp:22, evades left 4, enhance evade 1] skill Strike 5
Possible targets of Strike:
+ Assault 0 [Vigil att:5-4(weakened)=1 hp:2 cd:1]
+ Assault 1 [Vigil att:5 hp:10 cd:2]
+ Assault 2 [Vigil att:5 hp:11 cd:3]
Assault 1 [Crogall Static att:5+7(rallied)=12 hp:22, evades left 4, enhance evade 1] Strike (5) on Assault 0 [Vigil att:5-4(weakened)=1 hp:2 cd:1]
Assault 0 [Vigil att:5-4(weakened)=1 hp:2 cd:1] takes 5 damage
Assault 0 [Vigil att:5-4(weakened)=1 hp:0 cd:1] dies
Evaluating Assault 1 [Crogall Static att:5+7(rallied)=12 hp:22, evades left 4, enhance evade 1] skill Weaken all 2
Assault 1 [Crogall Static att:5+7(rallied)=12 hp:22, evades left 4, enhance evade 1] attacks Assault 1 [Vigil att:5 hp:10 cd:2] for 12-[3(armored)]=9 damage
Assault 1 [Vigil att:5 hp:10 cd:2] takes 9 damage
TURN 9 ends for Commander [Alaric hp:46]
</pre>
