### ISSUE TITLE
debug options

### ISSUE THREAD

**Issue by whatchamccallum** [zachanassian/tu_optimize#47]
Has something happened with the debug options? I am not getting the turn by turn results that I have seen you post in the past.

$ ./tu_optimize "Barracus, Starformer, Starformer, Omega Nexite, Tazerecca, Xeno Suzerain, Auger Bore, Arch Nova Elite, Steadfast Assailant, Deranged Fanatic, Elite Squadron" GT126k98 -e "Enfeeble 3" +v debug
Your Deck: Deck: SoKyO6+i-LB-MJ-SI-dD-dn-ep-uS
Barracus hp:45 legendary raider, Enhance Poison 2, Enfeeble all 1, Strike 1
  Starformer 6/12/2 xeno, leech 5, poison 3, Enfeeble all 2
  Starformer 6/12/2 xeno, leech 5, poison 3, Enfeeble all 2
  Omega Nexite 4/13/1 legendary raider, Strike 2, Weaken 3, Siege 4
  Tazerecca 2/15/1 legendary xeno, Heal xeno 5, Rally xeno 3, Jam 4
  Xeno Suzerain 5/20/3 xeno, armored 4, Weaken all 3, Strike all 2
  Auger Bore 6/13/2 legendary imperial, evade 3, Rally imperial 4, Jam 5
  Arch Nova Elite 4/17/2 legendary xeno, evade 3, inhibit 2, Strike all 2
  Steadfast Assailant 4/22/2 legendary imperial, berserk 2, Rally imperial 6, Protect imperial 5
  Deranged Fanatic 12/12/2 righteous, counter 5, Strike 4
  Elite Squadron 4/15/1 legendary imperial, pierce 5, Protect imperial 3, Strike 4

Enemy's Deck: Deck: QKkO+i-Ce-Dn-Dt-F3-F9-W1-dz
Typhon Vex hp:50 legendary raider, Enhance Berserk all 1, Rally raider 3, Siege all 1
  Bolt Crag 4/14/1 righteous, armored 4, berserk 3, evade 4
  Charincinerator 6/15/1 raider, berserk 2, counter 5, poison 2
  Havoc Genesis 8/14/2 raider, berserk 2, counter 4, pierce 6
  Judgment Nova 7/18/2 legendary raider, evade 3, Protect all raider 2, Jam 3
  Razogoth's Majesty 10/11/2 bloodthirsty, berserk 2, evade 4, Enfeeble 3
  Sacred Sanctuary 21/2 righteous, Heal all 3, Rally all 2, Weaken 4
  Sacred Sanctuary 21/2 righteous, Heal all 3, Rally all 2, Weaken 4
  Sculpted Aegis 4/20/3 imperial, armored 5, evade 2, Heal all 4
  Veiled Defiler 4/17/1 bloodthirsty, inhibit 2, leech 6, Rally bloodthirsty 4

Effect: Enfeeble 3
win%: 100 (1 / 1)
stall%: 0 (0 / 1)
loss%: 0 (0 / 1)

**Comment by zachanassian** [comment]
Was removed in Version 2.0.0
- Removed debug option for an overall performance gain of 15-20%

You can easliy add it yourself. Just remove line 5 #define NDEBUG in tyrant.h and compile again. You will get a version with debug option.
