### ISSUE TITLE
[BUG] Bane of Triumpf is ignored

### ISSUE THREAD

**Issue by CHaosGentle** [zachanassian/tu_optimize#55]
While using Sim: No change in percentages at all
While using Climb: Bane is not mentioned at all

Btw.: No problem with Bane of Truth though

**Comment by zachanassian** [comment]
Please add examples. What was the exact command. What cards are included in Ownedcards.txt, etc.

**Comment by CHaosGentle** [comment]
Oh darn. My mistake...
Typo in cardabbrs.txt. After correction everything works well.
Sorry

**Comment by zachanassian** [comment]
Thanks for the update.
